apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::440744219836:role/eksctl-k8sb30-cluster-01-nodegroup-NodeInstanceRole-TjwLdw7efVkL
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::009412611595:role/k8sb30-role
      username: k8sb30-role
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::440744219836:user/eks-admin
      username: eks-admin
      groups:
      - system: masters
kind: ConfigMap
